spring:
  banner:
    charset: UTF-8
    location: logo.txt
  output:
    ansi:
      enabled: detect
  datasource:
    url: "jdbc:mysql://10.2.10.2:3306/cloud"
    username: root
    password: 123456

openstack:
  url: "http://10.2.10.1:5000/v3"
  admin: "admin"
  password: "openstack2023"
  domain: "default"
  project_id: "b7ea1c378b0f4d68aa9673841bd2257f"
  # 浮动IP地址池所在的网络的ID
  network_id: "7e00a9b1-1735-4bcb-8dd9-04aac1e55b67"
  LAN_network_id: "b7f11dec-3658-4a90-bc6c-82f468961be6"
  # 创建云桌面实例最大等待时间（单位：秒）
  # 超时并不一定会导致创建失败，但是应用程序将不会跟踪创建状态，线程将会从线程池中释放
  create_instance_timeout: 600
# 线程池设置
thread-pool:
  desktop_creating:
    core_pool_size: 8
    max_pool_size: 16
    queue_capacity: 24


token:
  period: 7

sync:
  # 同步 OpenStack 数据库的周期（单位：秒）
  period: 5

logging:
  charset:
    console: utf-8
  pattern:
    console: "%clr(%d{yyyy年MM月dd日}){cyan} %clr(%d{HH:mm:ss.SSS}){yellow} === [%thread] === %clr(%-5level) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n"
  file:
    path: "./logs/"
    name: "application.log"
  level:
    root: info
    sql: info
    web: info