spring:
  banner:
    charset: UTF-8
    location: logo.txt
  output:
    ansi:
      enabled: always
  datasource:
    url: "jdbc:mysql://10.2.10.2:3306/cloud"
    username: root
    password: 123456

openstack:
  url: "http://10.2.10.1:5000/v3"
  admin: "admin"
  password: "openstack2023"
  project_id: "b7ea1c378b0f4d68aa9673841bd2257f"

token:
  period: 7

logging:
  charset:
    console: utf-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} === [%thread] === %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n"
  file:
    path: "./logs/"
    name: "application.log"
  level:
    root: info
    sql: info
    web: info